apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: golang-helloWorld
  labels:
    app: golang-helloWorld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: golang
        role: helloWorld
        tier: frontend
    spec:
      containers:
      - name: master
        image: index.docker.io/allysono/golang-helloWorld
        imagePullPolicy: Always
        command: ["echo", "Sucesso!"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3030

